language: node_js
node_js:
- '14'

install:
- echo 'Installing dependencies'
- npm ci

script:
- echo 'Running tests'
- npm test

- echo 'Running coverage reporter'
- npm run report



after_script:
- echo 'Setting up coveralls'
- npm run coveralls

- echo 'pipelined mocha coverage information to coveralls'