language: node_js
node_js:
  - '14'
  - '13'

script:
- npm install
- echo 'dependencies installed, running tests'
- npm test

after_script:
- ./node_modules/.bin/jscoverage lib lib-cov
- ./node_modules/.bin/mocha test/test.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js