language: node_js
node_js:
- '14'

install:
- echo 'Installing dependencies'
- npm ci

script:
- echo 'Running tests'
- npm test

- echo 'Running coverage reporter'
- npm run report

after_script:
- echo 'Running overalls code coverage'
- npm run coveralls
- rm -rf ./coverage

- echo 'Pipelined mocha coverage information to coveralls'