language: node_js
node_js:
- node
install:
- npm ci
script:
- npm run test || true
- npm run report:lcov
- npm run coveralls
deploy:
  provider: s3
  access_key_id: AKIARGOXIGMNCG36TJ7Q
  secret_access_key: $ndDc+i+gwJ/BL+jBV8sYwKywYS5nZ8TL+tDegRNWLY7KH0Tw3fubUiUz20voZgxcsP8c94ok/3KL3+uPKYlLa8sdZPC/MNdtnFNKbSF+2VnBzV/B8JiYCSPeP59eO3nwzCLhbT7zxdRs8+Mmzul8HaGu3yCDzGNp4vsYWLKG8Njkjn/93RrG85o8nl85Oue5XshvFlK4UIz4XJybZOEukag5IJpbPabjj5U9Rc1isCYcYeLAU7lp29I8BC1HtKscSNeaVpT0Vykl7IpndIamECc8r9HKUnTtsvoo0t3fsSBO+VHgJ8iDie9d0Qop/Ougo2tZAvToeXPdWbyP1Etz5kBau4ZjZpBWyTFRlTI8G4j2YkdOI7ZGnd6r704XMhb3boIQ5i0Uwlc1ypKue0YyDAIiWZNaEDbnlb2/niiO9mJLkIVKwSgaGZP2sdgNkxve0OOQHRXOleAKpoe6KZUJYHzDbzO3TCdwcVnNu7QZsZTrsGFrhVkj3X65GInHi792pY9JE6xn5/CEQNw7e4+DM+DFcZutSoQKNB2GoAUFUVzeBpSlOrgGQYEulm53JZcTzVtYC6iiJsJjqSd+zwO2aeDAF/lHj73QOZz8yIfUpeyzUoGf9xgnfl9MO/Z1kuIflllI9pqAUXqhZ//wx0xs4HvrhpEq8f2HFuGdG/cOh/o=
  bucket: testing-course-bucket
  skip_cleanup: true
  acl: public_read
  local_dir: mochawesome-report
  on:
    branch: s3-aws
notifications:
  email: false
dd:
  secure: ndDc+i+gwJ/BL+jBV8sYwKywYS5nZ8TL+tDegRNWLY7KH0Tw3fubUiUz20voZgxcsP8c94ok/3KL3+uPKYlLa8sdZPC/MNdtnFNKbSF+2VnBzV/B8JiYCSPeP59eO3nwzCLhbT7zxdRs8+Mmzul8HaGu3yCDzGNp4vsYWLKG8Njkjn/93RrG85o8nl85Oue5XshvFlK4UIz4XJybZOEukag5IJpbPabjj5U9Rc1isCYcYeLAU7lp29I8BC1HtKscSNeaVpT0Vykl7IpndIamECc8r9HKUnTtsvoo0t3fsSBO+VHgJ8iDie9d0Qop/Ougo2tZAvToeXPdWbyP1Etz5kBau4ZjZpBWyTFRlTI8G4j2YkdOI7ZGnd6r704XMhb3boIQ5i0Uwlc1ypKue0YyDAIiWZNaEDbnlb2/niiO9mJLkIVKwSgaGZP2sdgNkxve0OOQHRXOleAKpoe6KZUJYHzDbzO3TCdwcVnNu7QZsZTrsGFrhVkj3X65GInHi792pY9JE6xn5/CEQNw7e4+DM+DFcZutSoQKNB2GoAUFUVzeBpSlOrgGQYEulm53JZcTzVtYC6iiJsJjqSd+zwO2aeDAF/lHj73QOZz8yIfUpeyzUoGf9xgnfl9MO/Z1kuIflllI9pqAUXqhZ//wx0xs4HvrhpEq8f2HFuGdG/cOh/o=
