language: node_js
node_js:
- node

install:
  - echo 'Installing dependencies'
  - npm ci

script:
  - echo 'Running tests'
  - npm run test --silent

  - echo 'Running coverage reporter'
  - npm run report

  - echo 'Running overalls code coverage'
  - npm run coveralls
  - rm -rf ./coverage

  - echo 'Pipelined mocha coverage information to coveralls'

nofications:
  email: false