language: node_js
node_js:
  - '14'
  - '14.0'
  - '13'
  - '12'
  - '12.0'
  - '10'
  - '10.0'
  - '8'
  - '8.6'
cache: npm

install:
- npm ci

script:
- npm test
- npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master